#ifndef SHADOW_NATIVE_PRODUCTION_RUNTIME_RUNTIME_BOOTSTRAPPER_HPP
#define SHADOW_NATIVE_PRODUCTION_RUNTIME_RUNTIME_BOOTSTRAPPER_HPP

namespace Shadow {

int StartProductionRuntime();

}

#endif /* SHADOW_NATIVE_PRODUCTION_RUNTIME_RUNTIME_BOOTSTRAPPER_HPP */